name: Fetch and Display JSON

on:
  push:
    branches:
      - main  # 필요에 따라 브랜치를 조정하세요.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: Parameters 설정
      id: parameters
      run: |
        echo "numOfRows=144" >> $GITHUB_ENV
        echo "dataType=JSON" >> $GITHUB_ENV
        echo "pageNo=1" >> $GITHUB_ENV
        echo "base_date=20231022" >> $GITHUB_ENV
        # echo "base_time=1700" >> $GITHUB_ENV
        echo "nx=61" >> $GITHUB_ENV
        echo "ny=126" >> $GITHUB_ENV

    - name: base_time env 설정
      run: |
        current_hour=$(date +'%H')
        if [ $current_hour -eq 2 ]; then
          base_time="1100" >> $GITHUB_ENV
        elif [ $current_hour -eq 5 ]; then 
          base_time="1400" >> $GITHUB_ENV
        elif [ $current_hour -eq 8 ]; then
          base_time="1700" >> $GITHUB_ENV
        elif [ $current_hour -eq 11 ]; then
          base_time="2000" >> $GITHUB_ENV
        elif [ $current_hour -eq 14 ]; then
          base_time="2300" >> $GITHUB_ENV
        elif [ $current_hour -eq 17 ]; then
          base_time="0200" >> $GITHUB_ENV
        elif [ $current_hour -eq 20 ]; then
          base_time="0500" >> $GITHUB_ENV
        elif [ $current_hour -eq 23 ]; then
          base_time="0800" >> $GITHUB_ENV
        else
          echo "No parameters specified for the current time ($current_hour)"
          exit 1
        fi

    - name: Fetch JSON from URL
      env:
        OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
        PARAM1: ${{ env.numOfRows }}
        PARAM2: ${{ env.dataType }}
        PARAM3: ${{ env.pageNo }}
        PARAM4: ${{ env.base_date }}
        PARAM5: ${{ env.base_time }}
        PARAM6: ${{ env.nx }}
        PARAM7: ${{ env.ny }}
      run: |
        # 시크릿 값과 환경 변수로 설정된 파라미터를 사용하여 URL에서 JSON 데이터를 가져오고 출력 파일에 저장
        curl -s -o response.json "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst?serviceKey=$OPEN_API_KEY&numOfRows=$PARAM1&dataType=$PARAM2&pageNo=$PARAM3&base_date=$PARAM4&base_time=$PARAM5&nx=$PARAM6&ny=$PARAM7"

    - name: Display JSON Response
      run: |
        # JSON 파일 내용을 표시
        cat response.json

