name: Fetch and Display JSON

on:
  push:
    branches:
      - main  # 필요에 따라 브랜치를 조정하세요.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: 요청 및 JSON 파일 저장
      run: |
        curl -s -o response.json "YOUR_API_URL"
      env:
        YOUR_API_URL: ${{ secrets.OPEN_API_KEY }}  # GitHub Secrets에 API URL을 저장한 경우

    - name: 응답 JSON파일 출력
      run: |
        # JSON 파일 내용을 표시
        cat response.json